apiVersion: apps/v1
kind: Deployment
metadata: 
   name: javaapp-deploy
   labels:
     app: myjavaapp
spec:
   replicas: 3
   selector:
      matchLabels:
         app: myjavaapp
   template: 
     metadata:
       labels:
          app: myjavaapp
     spec:
      containers:
      - name: javaapp-container
        image: panka9922/myjavaapp27aug22:2

        ports:
        - containerPort: 8080