apiVersion: v1
kind: ReplicationController
metadata:
   name: myjava1-rc
spec:
  replicas: 3
  selector: 
    app: javaapp
    version: 2.6.3
  template:
    metadata:
       labels:
          app: javaapp
          version: 2.6.3
    spec:
       containers:
       -  name: myjava-container
          image: maha4iac/myjavaaplication:2
          ports: 
            - containerPort: 8080