apiVersion: v1
kind: Service
metadata:
 name: myjava-srv
 labels:
    app: myjavaapp
    
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
  selector:
    app: myjavaapp
   

